module.exports = {

	data: [
		//--Por ahora los municipios de la habana---------------------
		{ idmuni: 1, nombre: "Arroyo Naranjo", provId: 1, precioEnvio: 15.00},
		{ idmuni: 2, nombre: "Boyeros", provId: 1, precioEnvio: 20.00},
		{ idmuni: 3, nombre: "Centro Habana", provId: 1, precioEnvio: 25.00},
		{ idmuni: 4, nombre: "Cerro", provId: 1, precioEnvio: 30.00},
		{ idmuni: 5, nombre: "Cotorro", provId: 1, precioEnvio: 35.00},
		{ idmuni: 6, nombre: "Diez de Octubre", provId: 1, precioEnvio: 40.00},
		{ idmuni: 7, nombre: "Guanabacoa", provId: 1, precioEnvio: 45.00},
		{ idmuni: 8, nombre: "Habana del Este", provId: 1, precioEnvio: 50.00},
		{ idmuni: 9, nombre: "Habana Vieja", provId: 1, precioEnvio: 55.00},
		{ idmuni: 10, nombre: "La Lisa", provId: 1, precioEnvio: 60.00},
		{ idmuni: 11, nombre: "Marianao", provId: 1, precioEnvio: 65.00},
		{ idmuni: 12, nombre: "Playa", provId: 1, precioEnvio: 70.00},
		{ idmuni: 13, nombre: "Plaza de la Revolución", provId: 1, precioEnvio: 75.00},
		{ idmuni: 14, nombre: "Regla", provId: 1, precioEnvio: 80.00},
		{ idmuni: 15, nombre: "San Miguel del Padrón", provId: 1, precioEnvio: 85.00},
		//--------------------------------------------------------------
		/* 
		//--pinar del rio------------------------------
		{ idmuni: 1, nombre: "Consolación del Sur", provId: 1, precioEnvio: 3},
		{ idmuni: 2, nombre: "Guane", provId: 1, precioEnvio: 3},
		{ idmuni: 3, nombre: "La Palma", provId: 1, precioEnvio: 3},
		{ idmuni: 4, nombre: "Los Palacios", provId: 1, precioEnvio: 3},
		{ idmuni: 5, nombre: "Mantua", provId: 1, precioEnvio: 3},
		{ idmuni: 6, nombre: "Minas de Matahambre", provId: 1, precioEnvio: 3},
		{ idmuni: 7, nombre: "Pinar del Río", provId: 1, precioEnvio: 3},
		{ idmuni: 8, nombre: "San Juan y Martínez", provId: 1, precioEnvio: 3},
		{ idmuni: 9, nombre: "San Luis", provId: 1, precioEnvio: 3},
		{ idmuni: 10, nombre: "Sandino", provId: 1, precioEnvio: 3},
		{ idmuni: 11, nombre: "Viñales", provId: 1, precioEnvio: 3},
		//--Artemisa----------------------------------
		{ idmuni: 12, nombre: "Alquízar", provId: 2, precioEnvio: 3},
		{ idmuni: 13, nombre: "Artemisa", provId: 2, precioEnvio: 3},
		{ idmuni: 14, nombre: "Bauta", provId: 2, precioEnvio: 3},
		{ idmuni: 15, nombre: "Caimito", provId: 2, precioEnvio: 3},
		{ idmuni: 16, nombre: "Guanajay", provId: 2, precioEnvio: 3},
		{ idmuni: 17, nombre: "Güira de Melena", provId: 2, precioEnvio: 3},
		{ idmuni: 18, nombre: "Mariel", provId: 2, precioEnvio: 3},
		{ idmuni: 19, nombre: "San Antonio de los Baños", provId: 2, precioEnvio: 3},
		{ idmuni: 20, nombre: "Bahía Honda", provId: 2, precioEnvio: 3},
		{ idmuni: 21, nombre: "Candelaria", provId: 2, precioEnvio: 3},
		{ idmuni: 22, nombre: "San Cristóbal", provId: 2, precioEnvio: 3},
		//--La habana -----------------------------------
		{ idmuni: 23, nombre: "Arroyo Naranjo", provId: 3, precioEnvio: 15.00},
		{ idmuni: 24, nombre: "Boyeros", provId: 3, precioEnvio: 20.00},
		{ idmuni: 25, nombre: "Centro Habana", provId: 3, precioEnvio: 25.00},
		{ idmuni: 26, nombre: "Cerro", provId: 3, precioEnvio: 30.00},
		{ idmuni: 27, nombre: "Cotorro", provId: 3, precioEnvio: 35.00},
		{ idmuni: 28, nombre: "Diez de Octubre", provId: 3, precioEnvio: 40.00},
		{ idmuni: 29, nombre: "Guanabacoa", provId: 3, precioEnvio: 45.00},
		{ idmuni: 30, nombre: "Habana del Este", provId: 3, precioEnvio: 50.00},
		{ idmuni: 31, nombre: "Habana Vieja", provId: 3, precioEnvio: 55.00},
		{ idmuni: 32, nombre: "La Lisa", provId: 3, precioEnvio: 60.00},
		{ idmuni: 33, nombre: "Marianao", provId: 3, precioEnvio: 65.00},
		{ idmuni: 34, nombre: "Playa", provId: 3, precioEnvio: 70.00},
		{ idmuni: 35, nombre: "Plaza de la Revolución", provId: 3, precioEnvio: 75.00},
		{ idmuni: 36, nombre: "Regla", provId: 3, precioEnvio: 80.00},
		{ idmuni: 37, nombre: "San Miguel del Padrón", provId: 3, precioEnvio: 85.00},
		//--Mayabeque-----------------------------------------------
		{ idmuni: 38, nombre: "Batabanó", provId: 4, precioEnvio: 3},
		{ idmuni: 39, nombre: "Bejucal", provId: 4, precioEnvio: 3},
		{ idmuni: 40, nombre: "Güines", provId: 4, precioEnvio: 3},
		{ idmuni: 41, nombre: "Jaruco", provId: 4, precioEnvio: 3},
		{ idmuni: 42, nombre: "Madruga", provId: 4, precioEnvio: 3},
		{ idmuni: 43, nombre: "Melena del Sur", provId: 4, precioEnvio: 3},
		{ idmuni: 44, nombre: "Nueva Paz", provId: 4, precioEnvio: 3},
		{ idmuni: 45, nombre: "Quivicán", provId: 4, precioEnvio: 3},
		{ idmuni: 46, nombre: "San José de las Lajas", provId: 4, precioEnvio: 3},
		{ idmuni: 47, nombre: "San Nicolás de Bari", provId: 4, precioEnvio: 3},
		{ idmuni: 48, nombre: "Santa Cruz del Norte", provId: 4, precioEnvio: 3},
		//--Matanzas--------------------------------------------------
		{ idmuni: 49, nombre: "Calimete", provId: 5, precioEnvio: 3},
		{ idmuni: 50, nombre: "Cárdenas", provId: 5, precioEnvio: 3},
		{ idmuni: 51, nombre: "Ciénaga de Zapata", provId: 5, precioEnvio: 3},
		{ idmuni: 52, nombre: "Colón", provId: 5, precioEnvio: 3},
		{ idmuni: 53, nombre: "Jagüey Grande", provId: 5, precioEnvio: 3},
		{ idmuni: 54, nombre: "Jovellanos", provId: 5, precioEnvio: 3},
		{ idmuni: 55, nombre: "Limonar", provId: 5, precioEnvio: 3},
		{ idmuni: 56, nombre: "Los Arabos", provId: 5, precioEnvio: 3},
		{ idmuni: 57, nombre: "Martí", provId: 5, precioEnvio: 3},
		{ idmuni: 58, nombre: "Matanzas", provId: 5, precioEnvio: 3},
		{ idmuni: 59, nombre: "Pedro Betancourt", provId: 5, precioEnvio: 3},
		{ idmuni: 60, nombre: "Perico", provId: 5, precioEnvio: 3},
		{ idmuni: 61, nombre: "Unión de Reyes", provId: 5, precioEnvio: 3},
		//--Cienfuegos---------------------------------------------------
		{ idmuni: 62, nombre: "Abreus", provId: 6, precioEnvio: 3},
		{ idmuni: 63, nombre: "Aguada de Pasajeros", provId: 6, precioEnvio: 3},
		{ idmuni: 64, nombre: "Cienfuegos", provId: 6, precioEnvio: 3},
		{ idmuni: 65, nombre: "Cruces", provId: 6, precioEnvio: 3},
		{ idmuni: 66, nombre: "Cumanayagua", provId: 6, precioEnvio: 3},
		{ idmuni: 67, nombre: "Palmira", provId: 6, precioEnvio: 3},
		{ idmuni: 68, nombre: "Rodas", provId: 6, precioEnvio: 3},
		{ idmuni: 69, nombre: "Santa Isabel de las Lajas", provId: 6, precioEnvio: 3},
		//--Villa Clara-----------------------------------------------
		{ idmuni: 70, nombre: "Caibarien", provId: 7, precioEnvio: 3},
		{ idmuni: 71, nombre: "Camajuaní", provId: 7, precioEnvio: 3},
		{ idmuni: 72, nombre: "Cifuentes", provId: 7, precioEnvio: 3},
		{ idmuni: 73, nombre: "Corralillo", provId: 7, precioEnvio: 3},
		{ idmuni: 74, nombre: "Encrucijada", provId: 7, precioEnvio: 3},
		{ idmuni: 75, nombre: "Manicaragua", provId: 7, precioEnvio: 3},
		{ idmuni: 76, nombre: "Placetas", provId: 7, precioEnvio: 3},
		{ idmuni: 77, nombre: "Quemado de Güines", provId: 7, precioEnvio: 3},
		{ idmuni: 78, nombre: "Ranchuelo", provId: 7, precioEnvio: 3},
		{ idmuni: 79, nombre: "Remedios", provId: 7, precioEnvio: 3},
		{ idmuni: 80, nombre: "Sagua la Grande", provId: 7, precioEnvio: 3},
		{ idmuni: 81, nombre: "Santa Clara", provId: 7, precioEnvio: 3},
		{ idmuni: 82, nombre: "Santo Domingo", provId: 7, precioEnvio: 3},
		//--Sancti Spíritus-----------------------------------------
		{ idmuni: 83, nombre: "Cabaiguán", provId: 8, precioEnvio: 3},
		{ idmuni: 84, nombre: "Fomento", provId: 8, precioEnvio: 3},
		{ idmuni: 85, nombre: "Jatibonico", provId: 8, precioEnvio: 3},
		{ idmuni: 86, nombre: "La Sierpe", provId: 8, precioEnvio: 3},
		{ idmuni: 87, nombre: "Sancti Spíritus", provId: 8, precioEnvio: 3},
		{ idmuni: 88, nombre: "Taguasco", provId: 8, precioEnvio: 3},
		{ idmuni: 89, nombre: "Trinidad", provId: 8, precioEnvio: 3},
		{ idmuni: 90, nombre: "Yaguajay", provId: 8, precioEnvio: 3},
		//--Ciego de Ávila-----------------------------------------
		{ idmuni: 91, nombre: "Ciro Redondo", provId: 9, precioEnvio: 3},
		{ idmuni: 92, nombre: "Baraguá", provId: 9, precioEnvio: 3},
		{ idmuni: 93, nombre: "Bolivia", provId: 9, precioEnvio: 3},
		{ idmuni: 94, nombre: "Chambas", provId: 9, precioEnvio: 3},
		{ idmuni: 95, nombre: "Ciego de Ávila", provId: 9, precioEnvio: 3},
		{ idmuni: 96, nombre: "Florencia", provId: 9, precioEnvio: 3},
		{ idmuni: 97, nombre: "Majagua", provId: 9, precioEnvio: 3},
		{ idmuni: 98, nombre: "Morón", provId: 9, precioEnvio: 3},
		{ idmuni: 99, nombre: "Primero de Enero", provId: 9, precioEnvio: 3},
		{ idmuni: 100, nombre: "Venezuela", provId: 9, precioEnvio: 3},
		//--Camagüey--------------------------------------------
		{ idmuni: 101, nombre: "Camagüey", provId: 10, precioEnvio: 3},
		{ idmuni: 102, nombre: "Carlos Manuel de Céspedes", provId: 10, precioEnvio: 3},
		{ idmuni: 103, nombre: "Esmeralda", provId: 10, precioEnvio: 3},
		{ idmuni: 104, nombre: "Florida", provId: 10, precioEnvio: 3},
		{ idmuni: 105, nombre: "Guaimaro", provId: 10, precioEnvio: 3},
		{ idmuni: 106, nombre: "Jimagüayú", provId: 10, precioEnvio: 3},
		{ idmuni: 107, nombre: "Minas", provId: 10, precioEnvio: 3},
		{ idmuni: 108, nombre: "Najasa", provId: 10, precioEnvio: 3},
		{ idmuni: 109, nombre: "Nuevitas", provId: 10, precioEnvio: 3},
		{ idmuni: 110, nombre: "Santa Cruz del Sur", provId: 10, precioEnvio: 3},
		{ idmuni: 111, nombre: "Sibanicú", provId: 10, precioEnvio: 3},
		{ idmuni: 112, nombre: "Sierra de Cubitas", provId: 10, precioEnvio: 3},
		{ idmuni: 113, nombre: "Vertientes", provId: 10, precioEnvio: 3},
		//--Las Tunas---------------------------------------------------
		{ idmuni: 114, nombre: "Amancio Rodríguez", provId: 11, precioEnvio: 3},
		{ idmuni: 115, nombre: "Colombia", provId: 11, precioEnvio: 3},
		{ idmuni: 116, nombre: "Jesús Menéndez", provId: 11, precioEnvio: 3},
		{ idmuni: 117, nombre: "Jobabo", provId: 11, precioEnvio: 3},
		{ idmuni: 118, nombre: "Las Tunas", provId: 11, precioEnvio: 3},
		{ idmuni: 119, nombre: "Majibacoa", provId: 11, precioEnvio: 3},
		{ idmuni: 120, nombre: "Manatí", provId: 11, precioEnvio: 3},
		{ idmuni: 121, nombre: "Puerto Padre", provId: 11, precioEnvio: 3},
		//--Holguín----------------------------------------------------
		{ idmuni: 122, nombre: "Antilla", provId: 12, precioEnvio: 3},
		{ idmuni: 123, nombre: "Báguanos", provId: 12, precioEnvio: 3},
		{ idmuni: 124, nombre: "Banes", provId: 12, precioEnvio: 3},
		{ idmuni: 125, nombre: "Cacocum", provId: 12, precioEnvio: 3},
		{ idmuni: 126, nombre: "Calixto García", provId: 12, precioEnvio: 3},
		{ idmuni: 127, nombre: "Cueto", provId: 12, precioEnvio: 3},
		{ idmuni: 128, nombre: "Frank País", provId: 12, precioEnvio: 3},
		{ idmuni: 129, nombre: "Gibara", provId: 12, precioEnvio: 3},
		{ idmuni: 130, nombre: "Holguín", provId: 12, precioEnvio: 3},
		{ idmuni: 131, nombre: "Mayarí", provId: 12, precioEnvio: 3},
		{ idmuni: 132, nombre: "Moa", provId: 12, precioEnvio: 3},
		{ idmuni: 133, nombre: "Rafael Freyre", provId: 12, precioEnvio: 3},
		{ idmuni: 134, nombre: "Sagua de Tánamo", provId: 12, precioEnvio: 3},
		{ idmuni: 135, nombre: "Urbano Noris", provId: 12, precioEnvio: 3},
		//--Granma----------------------------------------------------
		{ idmuni: 136, nombre: "Bartolomé Masó", provId: 13, precioEnvio: 3},
		{ idmuni: 137, nombre: "Bayamo", provId: 13, precioEnvio: 3},
		{ idmuni: 138, nombre: "Buey Arriba", provId: 13, precioEnvio: 3},
		{ idmuni: 139, nombre: "Campechuela", provId: 13, precioEnvio: 3},
		{ idmuni: 140, nombre: "Cauto Cristo", provId: 13, precioEnvio: 3},
		{ idmuni: 141, nombre: "Guisa", provId: 13, precioEnvio: 3},
		{ idmuni: 142, nombre: "Jiguaní", provId: 13, precioEnvio: 3},
		{ idmuni: 143, nombre: "Manzanillo", provId: 13, precioEnvio: 3},
		{ idmuni: 144, nombre: "Media Luna", provId: 13, precioEnvio: 3},
		{ idmuni: 145, nombre: "Niquero", provId: 13, precioEnvio: 3},
		{ idmuni: 146, nombre: "Pilón", provId: 13, precioEnvio: 3},
		{ idmuni: 147, nombre: "Río Cauto", provId: 13, precioEnvio: 3},
		{ idmuni: 148, nombre: "Yara", provId: 13, precioEnvio: 3},
		//--Santiago de Cuba----------------------------------------
		{ idmuni: 149, nombre: "Contramaestre", provId: 14, precioEnvio: 3},
		{ idmuni: 150, nombre: "Guamá", provId: 14, precioEnvio: 3},
		{ idmuni: 151, nombre: "Julio Antonio Mella", provId: 14, precioEnvio: 3},
		{ idmuni: 152, nombre: "Palma Soriano", provId: 14, precioEnvio: 3},
		{ idmuni: 153, nombre: "San Luis", provId: 14, precioEnvio: 3},
		{ idmuni: 154, nombre: "Santiago de Cuba", provId: 14, precioEnvio: 3},
		{ idmuni: 155, nombre: "Segundo Frente", provId: 14, precioEnvio: 3},
		{ idmuni: 156, nombre: "Songo la Maya", provId: 14, precioEnvio: 3},
		{ idmuni: 157, nombre: "Tercer Frente", provId: 14, precioEnvio: 3},
		//--Guantánamo----------------------------------------------
		{ idmuni: 158, nombre: "Baracoa", provId: 15, precioEnvio: 3},
		{ idmuni: 159, nombre: "Caimanera", provId: 15, precioEnvio: 3},
		{ idmuni: 160, nombre: "El Salvador", provId: 15, precioEnvio: 3},
		{ idmuni: 161, nombre: "Guantánamo", provId: 15, precioEnvio: 3},
		{ idmuni: 162, nombre: "Imías", provId: 15, precioEnvio: 3},
		{ idmuni: 163, nombre: "Maisí", provId: 15, precioEnvio: 3},
		{ idmuni: 164, nombre: "Manuel Tames", provId: 15, precioEnvio: 3},
		{ idmuni: 165, nombre: "Niceto Pérez", provId: 15, precioEnvio: 3},
		{ idmuni: 166, nombre: "San Antonio del Sur", provId: 15, precioEnvio: 3},
		{ idmuni: 167, nombre: "Yateras", provId: 15, precioEnvio: 3},
		//--Municipio especial Isla de la Juventud -------------------
		{ idmuni: 168, nombre: "Isla de la Juventud", provId: 16, precioEnvio: 3}, */
	],

	async create () {
		await _database.zunpc.model.municipio.bulkCreate(this.data);
	},
};