module.exports = {

	data: [
		{ id: 101, name: "Obtener los productos ", show: 1 },
		{ id: 102, name: "Obtener un prodcuto determinado", show: 1 },
		{ id: 103, name: "Editar Producto", show: 1 },
		{ id: 104, name: "Adicionar producto", show: 1 },
		{ id: 105, name: "Eliminar Producto", show: 1 },
		{ id: 106, name: "Buscar Productos", show: 1 },
		{ id: 107, name: "Obtener Tipo de producto", show: 1 },
		{ id: 108, name: "Obtener materiales por tipo de Producto", show: 1 },
		{ id: 109, name: "Obtener materiales por id", show: 1 },
		{ id: 110, name: "Obtener Filtros", show: 1 },
		{ id: 111, name: "Obtener Filtros por id", show: 1 },
		{ id: 112, name: "Obtener todos los servicios", show: 1 },
		{ id: 113, name: "Obtener un servicios determinado", show: 1 },
		{ id: 114, name: "Adicionar Servicio", show: 1},
		{ id: 115, name: "Editar Servicio", show: 1 },
		{ id: 116, name: "Eliminar Servicio", show: 1 },
		{ id: 117, name: "Buscar Servicio", show: 1 },
		{ id: 118, name: "Obtener tipo producto materiales", show: 1 },
		{ id: 119, name: "Obtener un tipo producto material determinado", show: 1 },
		{ id: 120, name: "Editar tipo producto material", show: 1 },
		{ id: 121, name: "Adicionar tipo producto material", show: 1 },
		{ id: 122, name: "Eliminar tipo producto material", show: 1 },
		{ id: 123, name: "Obtener tipo de producto", show: 1 },
		{ id: 124, name: "Obtener Materiales por tipo de producto ", show: 1 },
		{ id: 125, name: "Obtener materiales por id del Material", show: 1 },
		{ id: 126, name: "Obtener todos los Filtros", show: 1 },
		{ id: 127, name: "Obtener Filtros por id", show: 1 },
		{ id: 128, name: "Obtener todas las compras", show: 1 },
		{ id: 129, name: "obtener una compra determinado ", show: 0 },
		{ id: 130, name: "Adicionar compra", show: 0 },
		{ id: 131, name: "Eliminar compra", show: 0 },
		{ id: 132, name: "Editar compra", show: 1 },
		{ id: 133, name: "Buscar Compra", show: 1 },
		{ id: 134, name: "Obtener todos los usuarios", show: 1 },
		{ id: 135, name: "Obtener un usuario determinado", show: 1 },
		{ id: 136, name: "Desactivar usuario", show: 0 },
		{ id: 137, name: "Adicionar usuario", show: 0 },
		{ id: 138, name: "Ver Notificaciones", show: 0 },
		{ id: 139, name: "Editar Notificaciones", show: 0 },
		{ id: 140, name: "Eliminar Notificaciones", show: 0 },
		{ id: 141, name: "Cargar Puntos de Ventas", show: 1 },
		{ id: 142, name: "Consultar Cargos", show: 1 },
		{ id: 143, name: "Ver Restaurantes", show: 1 },
		{ id: 144, name: "Seleccionar Restaurantes", show: 1 },
		{ id: 145, name: "Adicionar Restaurantes", show: 1 },
		{ id: 146, name: "Editar Restaurantes", show: 1 },
		{ id: 147, name: "Eliminar Restaurantes", show: 1 },
		{ id: 148, name: "Ver Reservaciones De Restaurantes", show: 1 },
		{ id: 149, name: "Seleccionar Reservaciones De Restaurantes", show: 1 },
		{ id: 150, name: "Adicionar Reservaciones De Restaurantes", show: 1 },
		{ id: 151, name: "Eliminar Reservaciones De Restaurantes", show: 1 },
		{ id: 152, name: "Descargar Carta De Restaurantes", show: 1 },
		{ id: 153, name: "Ver Directorio", show: 1 },
		{ id: 154, name: "Adicionar Directorios", show: 1 },
		{ id: 155, name: "Editar Directorios", show: 1 },
		{ id: 156, name: "Eliminar Directorios", show: 1 },
		{ id: 157, name: "Ver Servicios Hoteleros", show: 1 },
		{ id: 158, name: "Adicionar Servicios Hoteleros", show: 1 },
		{ id: 159, name: "Editar Servisios Hoteleros" , show: 1},
		{ id: 160, name: "Eliminar Servicios Hoteleros", show: 1 },
		{ id: 161, name: "Ver Servicios Opcionales", show: 1 },
		{ id: 162, name: "Adicionar Servicios Opcionales", show: 1 },
		{ id: 163, name: "Editar Servicios Opcionales", show: 1 },
		{ id: 164, name: "Eliminar Servicios Opcionales", show: 1 },
		{ id: 165, name: "Ver Tasas de Cambio", show: 1 },
		{ id: 166, name: "Editar Tasas de Cambio", show: 1 },
		{ id: 167, name: "Cargar Tasas de Cambio", show: 1 },
		{ id: 168, name: "Ver Rangos de Reservas", show: 1 },
		{ id: 169, name: "Ver Entidades", show: 0 },
		{ id: 170, name: "Adicionar Entidades", show: 0 },
		{ id: 171, name: "Editar Entidades", show: 0 },
		{ id: 172, name: "Eliminar Entidades", show: 0 },
		{ id: 173, name: "Cargar Entidades", show: 1 },
		{ id: 174, name: "Cargar Promos", show: 1 },
		{ id: 175, name: "Adicionar Promos", show: 1 },
		{ id: 176, name: "Editar Promos", show: 1 },
		{ id: 177, name: "Eliminar Promos", show: 1 },
		{ id: 178, name: "Ver Promos", show: 1 },
		{ id: 179, name: "Ver Logs", show: 0 },
	],

	async create () {
		await _database.zunpc.model.permission.bulkCreate(this.data);
	}

};
